In [1]:
import numpy as np
import pandas as pd

In [2]:
url = "https://datafaculty.s3.us-east-2.amazonaws.com/chicago/nyt.frame.csv"
data = pd.read_csv(url)

In [3]:
data.head()

class.labels        X.  X.d  X.nd       X.s      X.th  X.this         a  \
0          art  0.008707  0.0   0.0  0.000000  0.009251     0.0  0.007564   
1          art  0.005848  0.0   0.0  0.000000  0.000000     0.0  0.001418   
2          art  0.016036  0.0   0.0  0.011403  0.000000     0.0  0.010063   
3          art  0.026415  0.0   0.0  0.000000  0.000000     0.0  0.008677   
4          art  0.007285  0.0   0.0  0.011008  0.000000     0.0  0.008390   

   abandoned  abc  ...  yorkers  yorks       you  young  younger  your  youre  \
0        0.0  0.0  ...      0.0    0.0  0.000000    0.0      0.0   0.0    0.0   
1        0.0  0.0  ...      0.0    0.0  0.000000    0.0      0.0   0.0    0.0   
2        0.0  0.0  ...      0.0    0.0  0.000000    0.0      0.0   0.0    0.0   
3        0.0  0.0  ...      0.0    0.0  0.000000    0.0      0.0   0.0    0.0   
4        0.0  0.0  ...      0.0    0.0  0.048151    0.0      0.0   0.0    0.0   

   youth  youthful   yu  
0    0.0       0.0  0.0  
1    0.0       0.0  0.0  
2    0.0       0.0  0.0  
3    0.0       0.0  0.0  
4    0.0       0.0  0.0  

[5 rows x 4432 columns]

In [4]:
data.shape

(102, 4432)

In [5]:
data['class.labels'].unique()

array(['art', 'music'], dtype=object)

In [7]:
import sklearn.decomposition as decomp

In [8]:
decompose = decomp.PCA(n_components = 50)

In [11]:
x = data.drop("class.labels", axis = 1)

In [12]:
decompose.fit(x)

PCA(copy=True, iterated_power='auto', n_components=50, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [13]:
decompose.components_

array([[-0.02694065, -0.04125824,  0.0069695 , ..., -0.00053028,
         0.0075259 , -0.00521438],
       [ 0.00420554, -0.00219802, -0.00340105, ...,  0.00496524,
        -0.00722542, -0.00607281],
       [ 0.04465877,  0.02567317,  0.00847306, ..., -0.00323756,
        -0.00429873, -0.00793915],
       ...,
       [ 0.01412902,  0.02556062, -0.01744403, ...,  0.00407748,
         0.01547471,  0.00837637],
       [ 0.01360439,  0.03843162, -0.01401103, ..., -0.00938467,
         0.01555365,  0.00838747],
       [ 0.02507464,  0.01651583,  0.02584714, ..., -0.00230493,
         0.00849791,  0.01074877]])

In [14]:
decompose.components_.shape

(50, 4431)

In [15]:
decompose.explained_variance_ ## eigen values

array([0.01988289, 0.01861809, 0.01723527, 0.01534565, 0.01437065,
       0.01389864, 0.01300251, 0.01275392, 0.0121597 , 0.01192065,
       0.01180664, 0.01163543, 0.01150265, 0.01138849, 0.01129077,
       0.01114976, 0.01098779, 0.01090328, 0.01084515, 0.01073628,
       0.01070558, 0.01057001, 0.01043106, 0.01040633, 0.01033313,
       0.01023072, 0.01012763, 0.01002812, 0.00993268, 0.0099177 ,
       0.00982988, 0.00981457, 0.00972382, 0.00962572, 0.00960634,
       0.00952928, 0.00948394, 0.00937489, 0.00937236, 0.00931361,
       0.00922834, 0.00913032, 0.00906599, 0.00900525, 0.00896274,
       0.00884562, 0.00875559, 0.00868129, 0.00861602, 0.0085708 ])

In [16]:
decompose.explained_variance_ratio_

array([0.0209328 , 0.0196012 , 0.01814537, 0.01615597, 0.01512949,
       0.01463255, 0.0136891 , 0.01342738, 0.01280178, 0.01255011,
       0.01243008, 0.01224983, 0.01211004, 0.01198986, 0.01188697,
       0.01173852, 0.01156799, 0.01147903, 0.01141782, 0.0113032 ,
       0.01127088, 0.01112815, 0.01098186, 0.01095583, 0.01087877,
       0.01077095, 0.01066241, 0.01055765, 0.01045717, 0.0104414 ,
       0.01034894, 0.01033283, 0.01023729, 0.010134  , 0.0101136 ,
       0.01003246, 0.00998474, 0.00986993, 0.00986726, 0.00980541,
       0.00971564, 0.00961244, 0.00954471, 0.00948077, 0.00943601,
       0.00931271, 0.00921793, 0.0091397 , 0.00907098, 0.00902337])

In [17]:
decompose.explained_variance_ratio_.cumsum()

array([0.0209328 , 0.040534  , 0.05867937, 0.07483534, 0.08996483,
       0.10459737, 0.11828647, 0.13171386, 0.14451564, 0.15706575,
       0.16949583, 0.18174566, 0.1938557 , 0.20584555, 0.21773253,
       0.22947105, 0.24103904, 0.25251807, 0.26393589, 0.27523909,
       0.28650997, 0.29763812, 0.30861999, 0.31957582, 0.33045459,
       0.34122554, 0.35188795, 0.3624456 , 0.37290277, 0.38334417,
       0.39369311, 0.40402594, 0.41426323, 0.42439723, 0.43451083,
       0.44454329, 0.45452803, 0.46439796, 0.47426522, 0.48407063,
       0.49378627, 0.50339872, 0.51294343, 0.5224242 , 0.53186021,
       0.54117292, 0.55039084, 0.55953054, 0.56860153, 0.5776249 ])

In [18]:
pca_data = decompose.transform(x)

In [19]:
pca_data.shape

(102, 50)

In [ ]:
#Exploratory device

In [21]:
decompose.components_[0,:]

array([-0.02694065, -0.04125824,  0.0069695 , ..., -0.00053028,
        0.0075259 , -0.00521438])

In [25]:
ind = x.columns
pd.Series(decompose.components_[0,:], index=ind).sort_values().head(7)

music       -0.109681
trio        -0.084132
theater     -0.081055
orchestra   -0.066403
composers   -0.058693
opera       -0.057621
theaters    -0.055302
dtype: float64

In [26]:
pd.Series(decompose.components_[1,:], index=ind).sort_values().head(7)

art         -0.152789
museum      -0.121245
images      -0.093313
artists     -0.092161
donations   -0.075356
painting    -0.074673
museums     -0.072591
dtype: float64

In [32]:
def get_variance(n, data):
    decompose = decomp.PCA(n_components = n)
    x = data.drop("class.labels", axis=1)
    decompose.fit(x)
    return decompose.explained_variance_ratio_.cumsum()[-1]

In [34]:
get_variance(75, data)

0.8035249271633162